Ac=input('enter the carrier signal amplitude');
Am=input('enter the message signal amplitude');
Fc=input('enter the frequency of  carier signal');
Fm=input('enter the frequency of  message signal');
Ma=input('enter modulation index');
t=(0:0.01:500);
y1=sin(2*pi*Fc*t);
y2=sin(2*pi*Fm*t);
y3=y1.*(1+Ma*y2);
subplot(3,1,1);
plot(t,y1);
xlabel ('time');
ylabel('Amplitude');
title('Carier Signal');
subplot(3,1,2);
plot(t,y2);
xlabel ('time');
ylabel('Amplitude');
title('Message Signal');
subplot(3,1,3);
plot(t,y3);
xlabel('time');
ylabel('Amplitude');
title('Modulated Signal');
